name = "MOModelingExtensions"
uuid = "056feff0-ae66-11e9-21b4-513c564917ea"
authors = ["Thibaut Cuvelier <cuvelier.thibaut@gmail.com>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
